// flow-typed signature: b8d5a68b619f2a4f3b41a5d19917dfe9
// flow-typed version: <<STUB>>/magic-grid_v^3.2.4/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'magic-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'magic-grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'magic-grid/dist/magic-grid.cjs' {
  declare module.exports: any;
}

declare module 'magic-grid/dist/magic-grid.esm' {
  declare module.exports: any;
}

declare module 'magic-grid/dist/magic-grid.min' {
  declare module.exports: any;
}

declare module 'magic-grid/rollup.config' {
  declare module.exports: any;
}

declare module 'magic-grid/src/index' {
  declare module.exports: any;
}

declare module 'magic-grid/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'magic-grid/dist/magic-grid.cjs.js' {
  declare module.exports: $Exports<'magic-grid/dist/magic-grid.cjs'>;
}
declare module 'magic-grid/dist/magic-grid.esm.js' {
  declare module.exports: $Exports<'magic-grid/dist/magic-grid.esm'>;
}
declare module 'magic-grid/dist/magic-grid.min.js' {
  declare module.exports: $Exports<'magic-grid/dist/magic-grid.min'>;
}
declare module 'magic-grid/rollup.config.js' {
  declare module.exports: $Exports<'magic-grid/rollup.config'>;
}
declare module 'magic-grid/src/index.js' {
  declare module.exports: $Exports<'magic-grid/src/index'>;
}
declare module 'magic-grid/src/utils.js' {
  declare module.exports: $Exports<'magic-grid/src/utils'>;
}
