// flow-typed signature: b280532b45549b20f7e5664c09f6c40d
// flow-typed version: <<STUB>>/magic-grid-react_v^0.3.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'magic-grid-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'magic-grid-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'magic-grid-react/dist/magic-grid-react.cjs' {
  declare module.exports: any;
}

declare module 'magic-grid-react/dist/magic-grid-react.es' {
  declare module.exports: any;
}

declare module 'magic-grid-react/dist/magic-grid-react.iife' {
  declare module.exports: any;
}

declare module 'magic-grid-react/dist/magic-grid-react.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'magic-grid-react/dist/magic-grid-react.cjs.js' {
  declare module.exports: $Exports<'magic-grid-react/dist/magic-grid-react.cjs'>;
}
declare module 'magic-grid-react/dist/magic-grid-react.es.js' {
  declare module.exports: $Exports<'magic-grid-react/dist/magic-grid-react.es'>;
}
declare module 'magic-grid-react/dist/magic-grid-react.iife.js' {
  declare module.exports: $Exports<'magic-grid-react/dist/magic-grid-react.iife'>;
}
declare module 'magic-grid-react/dist/magic-grid-react.umd.js' {
  declare module.exports: $Exports<'magic-grid-react/dist/magic-grid-react.umd'>;
}
