// @flow
export const GET_NEW_HOME_SECTION: string = "GET_NEW_HOME_SECTION";
export const GET_HOME_SECTION_INDEX: string = "GET_HOME_SECTION_INDEX";

export const GET_NEW_FOOTER_SECTION: string = "GET_NEW_FOOTER_SECTION";
export const GET_FOOTER_SECTION_INDEX: string = "GET_FOOTER_SECTION_INDEX";

export const GET_NEW_APP_SECTION: string = "GET_NEW_APP_SECTION";
export const GET_APP_SECTION_INDEX: string = "GET_APP_SECTION_INDEX";

export const GET_NAVIGATION_DATA: string = "GET_NAVIGATION_DATA";
